name: OpenDev CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  ci:
    uses: iamangus/opendev/.github/workflows/opendev-ci.yml@v2
    with:
      profile: auto
